### ISSUE TITLE
Current data test

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#1]
## Description

The Aid Transparency Index only considers current data. We define current data as:

- ongoing activities, or
- activities with planned end dates within the last 12 months, or
- activities with actual end dates within the last 12 months, or
- activities with disbursement, expenditure or commitment transaction dates within the last 12 months

Note: “The last 12 months” is taken from the end of data collection.
## Current test

```python
Either:
  `activity-status` is 2
o​r
  `activity-date[@type="3"]/@iso-date | activity-date[@type="3"]/text()`
  i​s less than 12 months ago
o​r
  `activity-date[@type="4"]/@iso-date | activity-date[@type="4"]/text()`
  i​s less than 12 months ago
o​r
  fo​r at least one
   `transaction[transaction-type/@code="2"] | transaction[transaction-type/@code="3"] | transaction[transaction-type/@code="4"]`,
   `transaction-date/@iso-date` i​s less than 12 months ago`
```

**Comment by YohannaLoucheur** [comment]
The description is less precise than the tests; suggest clarifying e.g.
- All activities with a status of Implementation;
- All activities (irrespective of status) with a planned or actual end date within the last 12 months
- All activities (irrespective of status) with transaction dates within the last 12 months 

Also, this description and test do not match the definition in the 2022 Technical Paper, which stated "current is defined as published within 12-months". Date of publication is not necessarily the same as activity status or end dates.

**Comment by publishwhatyoufund** [comment]
We agree that the description can be updated to properly reflect the detail of the test. 

The rule-set tests are aiming to capture activities published within the last 12 months. This statement could be updated to 
'Current is defined as an activity that was published, updated or has been active in the last 12 months.’

**Comment by YohannaLoucheur** [comment]
The proposed rewording is still not aligned on the test, since the latter does not look at whether an activity was **published** within a certain period. The test only looks at status, end dates and transaction dates - none of which relate to when the activity was published.

**Comment by YohannaLoucheur** [comment]
Sorry to keep this exchange going, but the word "updated" can still create confusion. The test looks at transactions but not at other potential types of updates - for instance updating results, improving the description, correcting the geo-location, etc. (this list could go on!). 
Why not simply say "current is defined as an activity that was in implementation, had transactions or ended in the last 12 months."

**Comment by publishwhatyoufund** [comment]
@YohannaLoucheur  thanks for the suggestion, we will take this forward and add this more detailed description to the technical paper.
