### ISSUE TITLE
Project budget

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#10]
## Description

The overall financial cost or amount is a summary total financial sum for the activity.

This is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the default aid type code is administrative costs (G01).

## Current test

Firstly:
```python
Budget available forward annually
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2 or 3
    And `default-aid-type/@code` is not G01
    And `activity-date[@type="3" or @type="4" or @type="end-planned" or @type="end-actual"]/@iso-date` is at least 6 months ahead
    Then `budget | planned-disbursement` should be available forward annually
 ```
 
Secondly:
```python
Budget available forward quarterly
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2 or 3
    And `default-aid-type/@code` is not G01
    And `activity-date[@type="3" or @type="4" or @type="end-planned" or @type="end-actual"]/@iso-date` is at least 6 months ahead
    Then `budget | planned-disbursement` should be available forward quarterly
 ```

**Comment by YohannaLoucheur** [comment]
The description does not match the test (no mention of quarterly breakdown)

**Comment by publishwhatyoufund** [comment]
The description in the technical paper does include this:
‘The budget of the activity is the breakdown of the total financial commitment to the activity into forward looking annual and quarterly chunks.’
