### ISSUE TITLE
Commitments

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#12]
## Description

The overall financial cost or amount is a summary total financial sum committed for the activity.

This is only expected if the activity is in the implementation, completion or post-completion phase.

## Current test

```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    Then `transaction[transaction-type/@code="2" or transaction-type/@code="C"]` should be present
```

**Comment by publishwhatyoufund** [comment]
Currently the test for a transaction only checks for the presence of a value. The test can be modified to check for the current year as well so that any scores awarded for this test fairly reflect current data rather than awarding scores for transactions which may be several years past. 

This would align with the current data test and ensure that data is being regularly updated. 

Updated test:

Commitments
For each current activity,
if `activity-status/@code` is one of (2, 3, 4)
then `transaction/transaction-type[@code="2"]` should be present
AND transaction year should be *current year*

**Comment by kossoverpn** [comment]
MCC has concerns with this change as it penalizes a model with larger programs that are broken out into smaller activities for reporting. Our programs are composed of activities that have an ebb and flow of work and funds over their five-year lifecycle. Due to this, there are activities which are part of an active program but have not had any transactions in the past 12-months and will have transactions in the future. These are still active activities.

Additionally, we would like to clarify whether a ‘0’ value transaction would pass the test.

**Comment by Erik-Sida** [comment]
We have many activities that don't have any commitment for a certain year. Why do these have to have a transaction each year? Would a transaction with a 0 value these years be preferable?

**Comment by YohannaLoucheur** [comment]
As for the proposed change in the Disbursements indicator, the logic behind this proposed change is very unclear. We typically have only one commitment per activity, at the beginning; if the activity lasts several years, we would be penalized for not having new commitments. Why?? 
In addition, given the vary nature of commitments (an obligation to pay something in the future), activities in the Post-Completion stage are very unlikely to have recent commitments and should be excluded. Even at the Completion stage, recent commitments might be rare.

**Comment by FabioThomaBMZ** [comment]
From the modifications you've made to the commitment indicator, it seems you aim to verify two criteria for the Outgoing Commitment:

 1) There exists a valid @value.
  2) The associated IATI attribute @iso-date for Outgoing Commitments is within the last 12 months.

Is our understanding accurate?

If so, it's essential to note that our BMZ IATI Outgoing Commitments always indicate the start date of a project. This date remains consistent throughout the project's duration. In our records, this start date signifies when the commitment for the project value was made or when a contract was signed. Consequently, the Commitment @iso-date for a majority of BMZ data exceeds 12 months.

Given this context, modifying the @iso-date attribute annually, as suggested by your changes, would not be appropriate for our records. Such adjustments wouldn't reflect the accurate timeline of our commitments.

**Comment by RafaelRovaletti** [comment]
The 12 months period might not be relevant/applicable to all publishers. Some business models are biennial (for instance WHO) and the commitment is sometimes made at the beginning of the planned project. The proposed change would not be equitable to all publishers and would not necessarily represent a lack of transparency.

**Comment by hsd25** [comment]
The 12 months period is not applicable to our business model as we typically have only one commitment per activity and at the beginning.

**Comment by HermanvanLoon** [comment]
Many of our multiple year projects may have one commitment and several disbursements:
1 - contract is signed in year one. A commitment is done with the total contract value. The first disbursement is done.
2 - multiple disbursements are done in the subsequent years.

This means that it is unreasonable to expect that here will be a commitment each year.

**Comment by stevieflow** [comment]
I fully agree with all the feedback so far - this change would not be in line with established practices for many many organisations

Furthermore, my understanding of the ATI methodology is that the "current activity" is a separate, and cross-cutting, "test", as defined in https://github.com/pwyf/2024-Index-indicator-definitions/issues/1.  By bringing in an _additional_ attempt to further refine "current activity" here, there's a real risk of undermining and contradicting the wider methodology.

**Comment by publishwhatyoufund** [comment]
We agree that the proposed current year test for the commitment transaction is not suitable given the nature of commitment publishing
