### ISSUE TITLE
Budget alignment

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#14]
## Description

The budget alignment indicator helps to link the activity to the recipient country government’s own budget codes.

This is only expected if the activity is in the implementation, completion or post-completion phase, and if the aid type is not budget support. This is not expected if the aid type is budget support (A01 or A02) or if the default aid type code is administrative costs (G01).

The test follows the guidance on country budget alignment, found here on the IATI reference website: http://reference.iatistandard.org/203/activity-standard/overview/country-budget-alignment/

This guidance also includes the relevant CRS codelist guidance that will be used for this test.

## Current test

Firstly:
```python
   Capital spend is present
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02 or G01
    And `transaction/aid-type/@code` is not any of A01 or A02
    Then `capital-spend` should be present
```

Secondly:
```python
   Publish detailed CRS purpose codes in the sector field
      Given an IATI activity
     And the activity is current
     And `activity-status/@code` is one of 2, 3 or 4
     And `default-aid-type/@code` is not any of A01, A02 or G01
     And `transaction/aid-type/@code` is not any of A01 or A02
     Then `sector/@code` should be present
     And at least one `sector[not(@vocabulary) or @vocabulary="1"]/@code | transaction/sector[@vocabulary="1" or 
     not(@vocabulary)]/@code` should be on the Sector codelist
     And `sector/@code` is not any of 43010, 43050, 43081, 43082, 52010, 99810, 15110, 15111, 15112, 15114, 15130, 16010, 
     16061, 21010, 21020, 22010, 23110, 43030 or 43040
```

**Comment by YohannaLoucheur** [comment]
The proposed change makes sense
