### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#15]
## Description

The title of the activity is the name of the activity. This is preferably the formal name of the activity, but does not have to be.

## Current test

Title is present
```python
   Given an IATI activity
    And the activity is current
    Then `title[text() or narrative/text()]` should be present
```
 
Title has at least 10 characters
```python
   Given an IATI activity
    And the activity is current
    Then `title/text() | title/narrative/text()` should have at least 10 characters
 ```

**Comment by YohannaLoucheur** [comment]
Consider making the number of characters longer - 10 is very small to provide any meaningful information. Perhaps 15 or even 20.

The narrative field should include a language attribute - let's not make English the default. (this should apply to all narrative fields)

**Comment by stevieflow** [comment]
> The narrative field should include a language attribute - 

@YohannaLoucheur I understand your point, but it's also entirely legitimate to have a default language set at the IATI activity level, and then not be mandated to include this on specific narratives such as title (or description).

The test _could_ include a check to see if the language is therefore declared within the activity - but the test would need to look in the ``iati-activity`` [element](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/) initially

> let's not make English the default

It's entirely legitimate for an activity to have _any_ default language

**Comment by YohannaLoucheur** [comment]
Agree @stevieflow that an activity can had English as default. 
The general point is that the language should be declared, either as default or in specific elements.

**Comment by publishwhatyoufund** [comment]
Currently we will not be taking this suggestion forward as we have found many titles which can be short but also convey a meaning. 
The test for a language field is also not a requirement in the IATI standard
