### ISSUE TITLE
Planned Dates

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#17]
## Description

The planned dates are the dates that the activity is scheduled to start and end on.

## Current test

Planned start date is present
```python
   Given an IATI activity
    And the activity is current
    Then `activity-date[@type="1" or @type="start-planned"]` should be present
```

Planned end date is present
```python
   Given an IATI activity
    And the activity is current
    If 'finance-type/@code' is not any of 501, 433, 432, 1100, 201
    Then `activity-date[@type="3" or @type="end-planned"]` should be present
```

**Comment by YohannaLoucheur** [comment]
An additional useful test for data quality could be whether the planned end date is in the future (perhaps with some margin eg 90 days)

**Comment by hsd25** [comment]
@YohannaLoucheur normally we get an alert on this on the IATI validator no? but good one!

**Comment by publishwhatyoufund** [comment]
The current date test also picks up activities which have ended so this would not be a suitable test
