### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#22]
## Description

The sub-national geographic location is information about where the activity is located within a country.

This is only expected if the activity is in the implementation, completion or post-completion phase and if the activity has been identified to be sub-national in scope. 

This is not expected if the activity has been marked with the recipient region code 998 (bilateral/unspecified) - the intention is to exclude activities that do not have any geographic focus.

This is not expected if the default aid type code is administrative costs (G01).

This is not expectd if the activity is national or suprenational in scope by using the Activity Scope element. 

## Current test
Location (sub-national)
```python
   Given an IATI activity
    And the activity is current
    And the `activity-scope/@code` is one of 1, 2, 3 or 4*
    And `activity-status/@code` is one of 2, 3 or 4
    And `recipient-region/@code` is not 998
    And `default-aid-type/@code` is not G01, B01 or B02
    Then `location` should be present
``` 
Location (sub-national) coordinates or point
```python
   Given an IATI activity
    And the activity is current
    And the `activity-scope/@code` is one of 1, 2, 3 or 4*
    And `activity-status/@code` is one of 2, 3 or 4
    And `recipient-region/@code` is not 998
    And `default-aid-type/@code` is not G01, B01 or B02
    Then `location[coordinates or point]` should be present
```
* Exclusion based on the Scope element are only applied to organisations that we can confirm are using Scope to identify whether an activity has a subnational location.

**Comment by publishwhatyoufund** [comment]
We are considering changing the second part of this test to allow for Geo-names and other geographic vocabulary:

This second part of the test is limited to searching for only the latitude and longitude points as described by the IATI [point](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/point/) element. 

However, some publishers may want to describe their location with another type of descriptive vocabulary. There are two other descriptor elements which can support this: [Location-ID](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/location-id/) and [Location-administration](https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/location/administrative/) . Both of those allow publishers to include vocabularies from the [GeographicVocabulary codelist](https://iatistandard.org/en/iati-standard/203/codelists/geographicvocabulary/) which includes the use of geonames.

Updated test
Location (sub-national) coordinates or point
For each current activity,
if activity-scope/@code is not one of (1, 2, 3, 4)*
if `activity-status/@code` is one of (2, 3, 4)
and `recipient-region/@code` is not 998
And `default-aid-type/@code` is not any of B01, B02, F01, H01, H02, H03, H04, H05 or G01
    And `transaction/aid-type/@code` is not any of B01, B02, F01, H01, H02, H03, H04, H05 or G01
And `default-aid-type/@code` is not G01
Then one of `location/point` or `location/administrative` or `location/location-id`should be present 
IF `location/administrative` or `location/location-id` are present than should have a valid code from the ‘GeographicVocabulary codelist’ and should have a value
*Exclusions based on the Scope element are only applied to organisations that we can confirm are using Scope to identify whether an activity has a subnational location.

**Comment by YohannaLoucheur** [comment]
We fully support the proposed changes. 

Getting into the weeds: 
- Suggest to update the description to reflect the fact that several aid types are excluded beyond admin costs;
- Given the more detailed list of aid types excluded (both at default and transaction level), the following line is now redondent
"And default-aid-type/@code is not G01"

**Comment by HermanvanLoon** [comment]
The issue still exists that a donor can provide regional or even country specific funds to an organisation without knowing beforehand for which locations these funds are meant. It is in this case the receipient organisation who makes that decision and therefore only the recipient organisation can publish reliable location information.

**Comment by stevieflow** [comment]
Observation: this revised test makes a dependency on the ``activity-scope`` element being present, and having a conditional logic to the ``location`` element.  That is a change in logic, as it now involves two elements within an activity, whereas previously the test was only centred on one.  This change should be clearly communicated to publishers, so that any data changes can be planned (ie: for those that do not currently use ``activity-scope`` for various reasons).  

I'm not sure how the previous test behaved if the ``activity-scope`` was not published - perhaps this was skipped, rather than being a core requirement, as it now seems to be.

----------------

@HermanvanLoon - as an aside, and related to your point: would that use case still mean the donor could / should use the ``activity-scope`` [code of 5 or onwards](https://iatistandard.org/en/iati-standard/203/codelists/activityscope/) (to declare sub-national activity)?

For the IATI standard (not PWYF) - perhaps there may eventually be "scope" for a ``location-not-provided`` attribute, whereby publishers can declare why a location is not published (as we have in the ``budget`` element)

Thanks

**Comment by HermanvanLoon** [comment]
You are right Steven. The dependency on the activity-scope would solve the problem. When an activity, from the donors point of view, is not a sub-national activity, I would expect that only activity-scope 1,2,3 or 4 are used. Not sure if we need a 'location-not-provided' attribute.

**Comment by publishwhatyoufund** [comment]
The update to the location test to include the scope element as a dependency will not occur automaticaly across all publishers. There will be quality checking and verification of the scope element before scope can be applied as a filter. 
This will take place during the sampling phase of the review. 
If no scope element is present or if scope is not being used to identify the geographic location of the activity or if the scope is inaccurate then we will not apply this dependency. 

We agree that the exclusion of administrative aid types is a potential duplication of the same function as the scope filter however some publishers may not be using the scope element so we will leave this in place.
