### ISSUE TITLE
Aid Type

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#26]
## Description

The type of aid shows whether the activity is classed as budget support, a project, technical assistance, debt relief, administrative costs, and so on.

This can be either at the activity or transaction level, and is only expected if the activity is in the implementation, completion or post-completion phase.

## Current test
Firstly:
```python
For each current activity,
if `activity-status/@code` is one of (2, 3, 4)
then `default-aid-type` should be present
or `transaction/aid-type` should be present
```
Secondly:
```python
For each current activity,
if `activity-status/@code` is one of (2, 3, 4)
then at least one `default-aid-type/@code` should be on the AidType codelist
or at least one `transaction/aid-type/@code` should be on the AidType codelist
```

**Comment by publishwhatyoufund** [comment]
We are considering changing the aid type test to allow a wider aid type vocabulary range: 

The aid type test for Aid type is valid looks for a code from the OECD-DAC Aid Type code list. However, there are several other [aid type vocabularies](https://iatistandard.org/en/iati-standard/203/codelists/aidtypevocabulary/) which can be used including the Grand Bargain Earmarking Category; Earmarking Modality or the Tracking Cash and Voucher Assistance modality.

Updated test: 
Given an IATI activity
 And `activity-status/@code` is one of 2, 3 or 4
 Then every `default-aid-type/@code | transaction/aid-type/@code` should be on the AidType codelist OR the EarmarkingCategory codelist OR the CashandVoucherModalities codelist

**Comment by FabioThomaBMZ** [comment]
Based on the adjustments you've implemented to the aid type indicator and its associated IATI attribute @vocabulary, are we correct in understanding that projects would be penalized (or lose points) if they only feature an Aid Type @code without an accompanying @vocabulary?  

Historically, in our BMZ IATI data, we've only published the @codes for aid type, omitting the @vocabulary attribute. This approach was guided by the IATI standards, which stipulate that in the absence of a specified attribute, the default assumed value is always vocabulary 1 (OECD DAC). This is further supported by the IATI xsd schema that states, “A code for the vocabulary aid-type classifications. If omitted the Aid Type (OECD DAC) codelist is assumed. The code must be a valid value in the AidTypeVocabulary codelist.”  

Would you please confirm our understanding and provide guidance on the matter?

**Comment by publishwhatyoufund** [comment]
The update to this test will mean that we do still accept the standard Aid Type codes and that this is accepted as the default. The test only looks to widen the scope of vocabularies allowed. We agree that the lack of a vocabulary when the default aid type codes are used should not be a barrier in this test. 

Test to be re-worded and shard in the Technical paper

**Comment by markbrough** [comment]
I would argue against accepting one of the other vocabularies in this test. It's important that everyone uses a common codelist because otherwise it makes it difficult to use the data. In this case, the DAC codelist makes it possible to know whether an activity or transaction is e.g. budget support, project-type interventions, or technical assistance. The other vocabularies (earmarking, and cash/vouchers) don't provide this type of information.

If there were interest in capturing something around earmarking, it might be possible to design a methodology which looks for specific DAC aid types or Grand Bargain earmarking classifications -- see related discussion on that here: https://humportal.org/guidance/earmarking

**Comment by publishwhatyoufund** [comment]
Having further considered @markbrough 's comments, we agree that the main purpose of the IATI standard is to encourage consistent use of the IATI codelist. We are therefore are only amending the test to ensure it does not give a penalty to those agencies which choose to publish an additional aid type code list. The test will still look for and score the use of the default aid type code list,. 

Updated test below:
Scenario Outline: Aid type is present
    Given an IATI activity
     And the activity is current
     And `activity-status/@code` is one of 2, 3 or 4
     Then `default-aid-type[not(@vocabulary) or @vocabulary="1"] | transaction/aid-type[not(@vocabulary) or @vocabulary="1"]` should be present

  Scenario Outline: Aid type is valid
    Given an IATI activity
     And the activity is current
     And `activity-status/@code` is one of 2, 3 or 4
     Then every `default-aid-type[not(@vocabulary) or @vocabulary="1"]/@code | transaction/aid-type[not(@vocabulary) or @vocabulary="1"]/@code` should be on the AidType codelist
