### ISSUE TITLE
Networked data

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#29]
## Description

The Networked data indicator assesses how organisations provide information about other organisations participating in their activities. It is a three part test. Part 1 is the test previously used for the Implementer indicator:

## Current test
```python
Given an IATI activity
     And the activity is current
     And `activity-status/@code` is one of 2, 3 or 4
     Then `participating-org[@role="Implementing" or @role="4"]/@ref | participating-org[@role="Implementing" or @role="4"]/narrative/text()` should have at least 1 character.
```

Part 2 of the indicator assesses use of standardised references for participating organisations in activities. 

We look for references to organisations other than self-references to the publisher themselves. We look for these in their current activities, across the participating organisation roles (Funding, Accountable, Extending and Implementing)

We construct a list of organisation references that will pass the test. These consist of:
·        IATI organisation identifiers from the IATI publishers list
·        OECD DAC CRS Channel Codes that use the prefix ‘XM-DAC’, except for generic or non-specific organisation references 
         (such as “Developing country-based NGO” or “Multilateral Organisations”)
·        Organisation references that are constructed using a valid prefix from the list of [recognised prefixes.
](https://codelists.codeforiati.org/OrganisationRegistrationAgency/)

Each activity receives a percentage score calculated by taking the proportion of participating organisations that have valid references and the total number of participating organisations involved in the activity, i.e.:

Score per activity = (number of participating organisations with valid references) / (total number of participating organisations, excluding self references) 

These scores will then be averaged across an organisation’s activities to calculate the final score for this test.

Part 3 of the networked data test will see if a receiver organisation (name or reference) os reported in each activity transactions. 

Each activity will receive a percentage score based on the proportion of transactions that include a receiver name or reference. This will be calculated as follows:

Score per activity = (number of transactions that include either a receiver org. name or reference) / (total number of transactions, excluding self-references)

These scores will then be aggregated across an organisation’s activities to calculate the final score for this test. 

```python
Given an IATI activity 
And the activity is current 
And `activity-status/@code` is one of 2, 3 or 4 
And transaction-type/@code’ is one of 2 or 3 
Then for each transaction `transaction/receiver-org@ref or transaction/receiver-org/narrative/text()`` should be present. 
```

**Comment by sgaddam-unicef** [comment]
Organization reference list is unlikely to be complete, and it requires constant updating. Unless there is a pre-set date for the 'final' reference list, the assessment of this indicator would be inaccurate & unfair.

Suggest to drop references as a "must" as the partner may not be an IATI publisher, and use narrative (names of organizations and/or types of organizations)

**Comment by YohannaLoucheur** [comment]
The test seems to work as expected and we support the requirement to provide recognized references (such as CRS Channel Codes or registration agencies) in addition to names (ie narrative).
 
However, allowances should be made if a decision was made* not to publish the name of an organization - perhaps this could be ascertained as part of the sampling stage. 
* In which cases this should be indicated clearly (eg "Name whitheld"), rather than leaving the element blank.

**Comment by publishwhatyoufund** [comment]
Please refer to the guidance on the various IATI and CodeforIATI websites which explain how references can be standardised using the correct prefixes and references numbers. 
The references are important so organisations remain consistent in spite of spelling errors, name variations or changes of name.

We have allowed for redacted references in the guidance.
