### ISSUE TITLE
Annual Report

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#3]
## Description
Annual reports outline basic (normally aggregate) information about how aid was spent in the previous year, broken down by sector and/or country. This should be backward looking.

As previously, documents will be manually checked to verify that they contain the required information to score for the indicator.

## Current test

```python
`document-link/category[@code="B01"]` should be present
```

**Comment by YohannaLoucheur** [comment]
This should specify whether an online portal providing the required information would qualify as a "document".

**Comment by publishwhatyoufund** [comment]
We will look into examples of this, can @YohannaLoucheur  please provide the example referenced in this comment?

**Comment by YohannaLoucheur** [comment]
This is an example: https://www.international.gc.ca/transparency-transparence/international-assistance-report-stat-rapport-aide-internationale/dashboard-tableau-bord.aspx?lang=eng 
 It provides information on how aid was spent by country, sector, type of partner, etc. The most recent statistical report (and past ones) is available on the dashboard.

**Comment by publishwhatyoufund** [comment]
@YohannaLoucheur  Thank you for sharing this example. We are unable to accept statistical reports as documentation for the annual report. Several agencies publish both a statistical report and an annual report and these provide different insights into the annual work of an agency. The annual report should provide some narrative insights into the work of an agency for example by evaluating results against their stated yearly goals and strategies, which a statistical dashboard can not do.

**Comment by YohannaLoucheur** [comment]
Thank you for the clarification. The current description only mentions "how aid was spent in the previous year, broken down by sector and/or country" which is exactly what is presented in the statistical report. 
I suggest that the description be clarified based on your response:  "The annual report should provide some narrative insights into the work of an agency for example by evaluating results against their stated yearly goals and strategies."

**Comment by publishwhatyoufund** [comment]
@YohannaLoucheur  thanks for the suggestion, we will take this forward and add this more detailed descriptin to the technical paper.
