### ISSUE TITLE
Project Procurement

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#30]
## Description

Tenders are the individual contracts or proposals that have been put out to invite bids from companies or organisations that want to provide goods and services for an activity.

Contracts are the individual contract(s) signed with a company, organisation or individual that provides goods and services for the activity.

These can be either at the activity or transaction level, and is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the aid type is budget support (A01 or A02) or if the default aid type code is administrative costs (G01).

## Current test

Tender is present
```python
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02, B02 or G01
    And `transaction/aid-type/@code` is not any of A01, A02 or B02
    Then `document-link/category[@code="A10"]` should be present
```

Contract is present
```python  
   Given an IATI activity
    And the activity is current
    And `activity-status/@code` is one of 2, 3 or 4
    And `default-aid-type/@code` is not any of A01, A02, B02 or G01
    And `transaction/aid-type/@code` is not any of A01, A02 or B02
    Then `document-link/category[@code="A06"] | document-link/category[@code="A11"]` should be present
```

**Comment by YohannaLoucheur** [comment]
This indicator is very dependent on a donor's business model. In some cases, like GAC, most activities cannot be linked to a specific "tender" that could be included in the IATI data.

**Comment by hsd25** [comment]
It also depends on the type of activities. Sometimes for emergency aid, the contract and procurement are done by the executing agency and not the Bank. 
For some small amount or technical assistance, procurement plan are part of the appraisal reports, same as TORs to recruit consultants or companies for example.

**Comment by publishwhatyoufund** [comment]
The project procurement: tenders indicator checks for the presence or absence of a procurement tender. The indicator does allow some flexibility for different procurement policies: 

'Due to the difficulty with manually finding tenders linked to current activities, rather than looking for the specific tender, a review of the organisation’s overall calls for tenders is completed to check it is publishing them consistently and in-line with their procurement policy. For organisations that do not issue tenders related to aid projects (e.g. if procurement is undertaken by grantees or other implementing agencies), a statement explicitly clarifying this is required. '

This means that, if an activity falls into a policy exclusion such as falling below a value requirement for a policy tender process or some other allowed exclusion then as long as the activity states what this exclusion is, this is sufficient
