### ISSUE TITLE
Pre-project impact appraisals

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#32]
## Description

Pre-project impact appraisals explain the totality of positive and negative, primary and secondary effects expected to be produced by a development intervention.

This is only expected if the activity is in the implementation, completion or post-completion phase.

This is not expected if the default aid type code is administrative costs (G01).

## Current test
```python
 For each current activity,
if `activity-status/@code` is one of (2, 3, 4)
And `default-aid-type/@code` is not any of A01, A02, B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
    And `transaction/aid-type/@code` is not any of A01, A02, B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
then `document-link/category[@code="A01"]` should be present

```

**Comment by sgaddam-unicef** [comment]
As UNICEF adapts a results-based model, information similar to pre-project impact appraisals is available in various documents, such as Situation Analysis reports, Programme Strategy Notes and Country Programme documents and the theory of change (pathway to achieving results), potential risk, assumptions, and impact of the planned development interventions of the Country Programme are detailed. 

The definition of the indicator could be expanded to country level, as an intervention rarely has isolated impact. Since we do not work on project implementation in isolation, there does not always exist a pre-project impact appraisal for every intervention.

**Comment by YohannaLoucheur** [comment]
As for the indicator related to evaluations, this indicator should exclude core funding (B01 and B02) as they are not "activities" or "development interventions" per se and do not lend themselves to this type of appraisal.

**Comment by RafaelRovaletti** [comment]
WHO is operating through a biennial, standardized results-based management model, in which country offices (together with host country ministry of health) set programmatic priorities. From the public health perspective, this is considered a pre-project appraisal and published on WHO's institutional website. We hope this is receivable.

**Comment by hsd25** [comment]
It also depends on the type of environmental and social categories. For category 3 at the AfDB (no impact) no document is prepared. Only for category 1 for sure and sometimes for category 2. But there are ESCON sections and note in each appraisal reports of the activity.

**Comment by publishwhatyoufund** [comment]
The test for Pre-project impact appraisal checks for the presence of an assessment of the full positive and negative impacts of the project. 

This can be, for example: environmental, social or governance assessments. Any exclusion applied must be universally accepted and can not be applicable to only one or two agencies. A risk assessment is not suitable as it only assesses the risks to project success 

If @YohannaLoucheur can share an example of core funding which should be excluded we can check to see if this would be universally applicable 

@RafaelRovaletti  as long as the assessment includes a full positive and negative assessment of intervention programmatic priorities will be accepted. 

@hsd25  the indicator currently does accept a statement outlining that no impact assessment has been carried out

**Comment by YohannaLoucheur** [comment]
This would be an example: https://w05.international.gc.ca/projectbrowser-banqueprojets/project-projet/details/P009571001 
While we describe the expected results (a requirement in our system), these are very general and it would be difficult to assess the effect of Canada's contribution specifically.

**Comment by alexjtilley** [comment]
Hi @YohannaLoucheur - yes, B01, B02, B03 and B04 are all excluded from this test - see the text of the test above for the full set of exclusions.
