### ISSUE TITLE
Reviews and evaluations

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#33]
## Description

Evaluation documents consider what the activity achieved, whether the intended objectives were met, what the major factors influencing the achievement or non-achievement of the objectives were and an assessment of the impact, effect and value of the activity.

This is only expected if the activity is in the completion or post-completion phase. 

This is not expected if the default aid type code is administrative costs (G01).

## Current test
```python
   For each current activity,
   i​f `activity-status/@code` i​s one of (3, 4)
   a​nd `default-aid-type/@code` i​s n​ot G01
   o​r `document-link/category[@code="A07"]` is present
   then `document-link/category[@code="A07"]` should be present
```

**Comment by YohannaLoucheur** [comment]
This test should exclude core funding (B01, B02) as they are not "activities" with specific objectives that lend themselves to this type of evaluation.

**Comment by publishwhatyoufund** [comment]
The reviews and evaluations test checks for an assessment of impact of funds for an activity. This can be at the programme, country or activity level and is only expected at the end of the project. As some organisations may publish evaluations of core funding there is no universal exclusion which can be applied here. The indicator description states: 

‘Evaluation documents consider what the activity achieved. This can include, whether the intended objectives were met, what the major factors influencing the achievement or non-achievement of the objectives were and an assessment of the impact, effect and value of the activity.’

We are re-wording the indicator description to account for core funds:

‘Evaluation documents consider what the activity achieved **or what the impact of funding provided were**. This can include, whether the intended objectives were met, what the major factors influencing the achievement or non-achievement of the objectives were and an assessment of the impact, effect and value of the activity.’
